name: Build and publish container

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-test
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "ready!"