name: Publish container locally

on:
  push:
    branches: [ "main" ]  
  schedule:
      - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build new image
        run: |
          docker build -t storager --build-arg API_URL=https://test.moradev.dev/apps/storager .

      - name: Restart container
        run: |
          docker stop storager || true
          docker rm storager || true
          docker run -d --restart unless-stopped --name storager -p 45334:45334 storager